version: '3.8'

services:
  app:
    image: hugodef1/app:latest
    container_name: app
    ports:
      - "80:80"
    networks:
      - segregated-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-junia
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - segregated-network

networks:
  segregated-network:
    driver: bridge